config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|uk|ru/ do
    root to: 'home#show'
    get 'index.html', to: 'home#show'
    resources :lists, only: :index do
      resources :todos, only: :index
    end
    namespace :admin do
      root to: 'home#show'
      get 'readonly', to: 'home#readonly'
      resources :statuses
      resources :accesses
      resources :lists do
        resources :todos do
          get :readonly, on: :collection
          put :done, on: :member
        end
      end
    end

    # devise_for :users,
    #           path_names: {sign_in: 'login',
    #                        sign_out: 'logout',
    #                        password: 'secret',
    #                        sign_up: 'registration'},
    #           controllers: {sessions: 'users/sessions',
    #                         registrations: 'users/registrations',
    #                         passwords: 'users/passwords',
    #                         confirmations: 'users/confirmations',
    #                         unlocks: 'users/unlocks',
    #           }
    devise_for :users, skip: %i[sessions registrations passwords confirmations unlock]
    as :user do
      get 'login.html', to: 'users/sessions#new', as: :new_user_session
      post 'login.html', to: 'users/sessions#create', as: :user_session
      match 'logout.html', to: 'users/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

      get 'registration.html', to: 'users/registrations#new', as: :new_user_registration
      post 'registration.html', to: 'users/registrations#create', as: :user_registration
      get 'edit-registration.html', to: 'users/registrations#edit', as: :edit_user_registration
      patch 'registration.html', to: 'users/registrations#update', as: :patch_user_registration
      delete 'registration.html', to: 'users/registrations#destroy', as: :delete_user_registration
      delete 'remove-avatar/:id', to: 'users/registrations#destroy_avatar', as: :delete_user_avatar_registration

      get 'recover-password.html', to: 'users/passwords#new', as: :new_user_password
      post 'recover-password.html', to: 'users/passwords#create'
      get 'edit-recover-password.html', to: 'users/passwords#edit', as: :edit_user_password
      patch 'recover-password.html', to: 'users/passwords#update', as: :user_password
      put 'recover-password.html', to: 'users/passwords#update'

      get 'confirmation.html', to: 'users/confirmations#new', as: :new_user_confirmation
      get 'show-confirmation.html', to: 'users/confirmations#show', as: :user_confirmation
      post 'show-confirmation.html', to: 'users/confirmations#create'

      get 'unlock.html', to: 'users/unlocks#new', as: :new_user_unlock
      get 'show-unlock.html', to: 'users/unlocks#show', as: :user_unlock
      post 'show-unlock.html', to: 'users/unlocks#create'
    end

     match '*a', to: 'admin/errors#not_found', via: :all unless Rails.env.development?
     # match '*a', to: 'admin/errors#not_found', via: :all
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  belongs_to :user
  belongs_to :access
  has_many :todos, dependent: :destroy

  validates :name, presence: true
  default_scope { order(:created_at) }

  def todos_complete
    status_id = Status.find_by(name: 'Complete').id
    if todos.count.zero?
      0
    else
      (todos.where(status_id: status_id).count / todos.count.to_f).round(2) * 100
    end
  end
end

app/controllers/admin/lists_controller.rb
# frozen_string_literal: true

class Admin::ListsController < Admin::BaseController
  before_action :list, only: %i[show edit update destroy]

  def index
    @lists = current_user.lists.all
  end

  def new
    @list = current_user.lists.new
  end

  def show
  end

  def edit
  end

  def create
    @list = current_user.lists.new(list_params)
    if @list.save
      redirect_to admin_root_path
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to admin_root_path
    else
      render :edit
    end
  end

  def destroy
    flash[:error] = @list.errors.full_messages unless @list.destroy
    redirect_to admin_root_path
  end

  private

  def list
    @list ||= current_user.lists.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :access_id)
  end
end

app/views/admin/lists/_form.html.slim
= f.error_notification
= f.input :name,
        placeholder: t('activerecord.models.list.attributes.name.placeholder'),
        required: true,
        label: t('name'),
        wrapper: :horizontal_form

= f.input :access_id,
        as: :select,
        label: t('activerecord.models.access.one'),
        label_method: ->(obj){ t("activerecord.models.access.values.name.#{obj.name}") },
        value_method: :id,
        include_blank: true,
        wrapper: :horizontal_form,
        required: true,
        collection: Access.all

app/views/admin/lists/edit.html.slim
= content_for(:title, t('admin.lists.edit'))
= simple_form_for [:admin, @list] do |f|
  /! Main content
  .content
    .container-fluid
      /! /.container-fluid
      /! /.content
      .row
        .col-md-8
          .card.card-yellow
            .card-header
              = t('admin.lists.edit')
            .card-body
              / - if @list.image.attached?
              /   div style=("border: 1px solid #28A745; padding: 2px")
              /     = image_tag @list.image.variant(resize: '200'), alt: @list.name
              /   = t('admin.lists.remove')
              /   |  #{link_to t('do it'), destroy_image_admin_list_path(@list), method: :delete}
              /   p
              / - else
              /   p style=("border: 1px solid #28A745; padding: 2px")
              /     = image_tag 'backend/default-image.jpg', size: 200, alt: 'Photo Image'
              = render partial: 'form', locals: {f: f}
            .card-footer
              = link_to  admin_lists_path, class: 'btn btn-danger'
                = t(:cancel)
              = f.submit t(:save), class: 'btn btn-success pull-right'

app/views/admin/lists/index.html.slim
= content_for(:title, t('admin.lists.list'))
/! Main content
.content
  .container-fluid
    /! /.container-fluid
    /! /.content
    .row
      .col-md-6.col-md-offset-10
        = link_to new_admin_list_path, class: 'btn btn-success pull-right'
          i.fas.fa-plus
          |
          = t('admin.lists.add')
    .row
      p

    .row
      .col-12
        .card.card-yellow
          .card-header
            h3.card-title
              = t('admin.lists.list')
          /! /.card-header
          .card-body.p-0
            table.table.table-condensed
              thead
                tr
                  th style=("width: 30px")
                    = t('name')
                  th style=("width: 15px")
                    = t('action')

              tbody
                - @lists.each do |list|
                  tr
                    td
                      = list.name
                    td
                      .btn-row
                        .btn-group
                          = link_to raw('<i class="fas fa-list-ol"></i>'), admin_list_todos_path(list),
                                  class: 'btn btn-sm btn-warning',
                                  style: 'margin-right: 10px',
                                  title: t('admin.todos.list')
                          = link_to raw('<i class="far fa-edit"></i>'), edit_admin_list_path(list),
                                  class: 'btn btn-sm btn-warning',
                                  style: 'margin-right: 10px',
                                  title: t('edit')
                          = link_to raw('<i class="far fa-trash-alt"></i>'), admin_list_path(list),
                                  class: 'btn btn-sm btn-warning',
                                  style: 'margin-right: 10px',
                                  method: :delete,
                                  data: {confirm: t('confirm')},
                                  title: t('remove')

          /! /.card-body

app/views/admin/lists/new.html.slim
= content_for(:title, t('admin.lists.new'))
= simple_form_for [:admin, @list] do |f|
  /! Main content
  .content
    .container-fluid
      /! /.container-fluid
      /! /.content
      .row
        .col-md-8
          .card.card-yellow
            .card-header
              = t('admin.lists.new')
            .card-body
              = render partial: 'form', locals: {f: f}
            .card-footer
              = link_to  admin_lists_path, class: 'btn btn-danger'
                = t(:cancel)
              = f.submit t(:save), class: 'btn btn-success pull-right'