config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|uk|ru/ do
    root to: 'home#show'
    get 'index.html', to: 'home#show'
    resources :lists, only: :index do
      resources :todos, only: :index
    end
    namespace :admin do
      root to: 'home#show'
      get 'readonly', to: 'home#readonly'
      resources :statuses
      resources :accesses
      resources :lists do
        resources :todos do
          get :readonly, on: :collection
          put :done, on: :member
        end
      end
    end

    # devise_for :users,
    #           path_names: {sign_in: 'login',
    #                        sign_out: 'logout',
    #                        password: 'secret',
    #                        sign_up: 'registration'},
    #           controllers: {sessions: 'users/sessions',
    #                         registrations: 'users/registrations',
    #                         passwords: 'users/passwords',
    #                         confirmations: 'users/confirmations',
    #                         unlocks: 'users/unlocks',
    #           }
    devise_for :users, skip: %i[sessions registrations passwords confirmations unlock]
    as :user do
      get 'login.html', to: 'users/sessions#new', as: :new_user_session
      post 'login.html', to: 'users/sessions#create', as: :user_session
      match 'logout.html', to: 'users/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

      get 'registration.html', to: 'users/registrations#new', as: :new_user_registration
      post 'registration.html', to: 'users/registrations#create', as: :user_registration
      get 'edit-registration.html', to: 'users/registrations#edit', as: :edit_user_registration
      patch 'registration.html', to: 'users/registrations#update', as: :patch_user_registration
      delete 'registration.html', to: 'users/registrations#destroy', as: :delete_user_registration
      delete 'remove-avatar/:id', to: 'users/registrations#destroy_avatar', as: :delete_user_avatar_registration

      get 'recover-password.html', to: 'users/passwords#new', as: :new_user_password
      post 'recover-password.html', to: 'users/passwords#create'
      get 'edit-recover-password.html', to: 'users/passwords#edit', as: :edit_user_password
      patch 'recover-password.html', to: 'users/passwords#update', as: :user_password
      put 'recover-password.html', to: 'users/passwords#update'

      get 'confirmation.html', to: 'users/confirmations#new', as: :new_user_confirmation
      get 'show-confirmation.html', to: 'users/confirmations#show', as: :user_confirmation
      post 'show-confirmation.html', to: 'users/confirmations#create'

      get 'unlock.html', to: 'users/unlocks#new', as: :new_user_unlock
      get 'show-unlock.html', to: 'users/unlocks#show', as: :user_unlock
      post 'show-unlock.html', to: 'users/unlocks#create'
    end

     match '*a', to: 'admin/errors#not_found', via: :all unless Rails.env.development?
     # match '*a', to: 'admin/errors#not_found', via: :all
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
  belongs_to :list
  belongs_to :status

  validates :name, presence: true
  default_scope { order(:created_at) }
end

app/controllers/admin/todos_controller.rb
# frozen_string_literal: true

class Admin::TodosController < Admin::BaseController
  before_action :todo, only: %i[show edit update destroy]
  before_action :todos, only: %i[index new readonly]

  def index
  end

  def new
    @todo = @list.todos.new
  end

  def show
  end

  def edit
  end

  def create
    @todo = list.todos.new(todo_params)
    if @todo.save
      redirect_to admin_root_path
    else
      render :new
    end
  end

  def update
    if @todo.update(todo_params)
      redirect_to admin_root_path
    else
      render :edit
    end
  end

  def destroy
    flash[:error] = @todo.errors.full_messages unless @todo.destroy
    redirect_to admin_root_path
  end

  def done
    if todo.update(status_id: Status.find_by(name: params[:status_name]).id)
      redirect_to admin_root_path, notice: 'Todo was mark as Complete.' if params[:status_name] == 'Complete'
      redirect_to admin_root_path, notice: 'Todo is back to Incomplete.' if params[:status_name] == 'Incomplete'
    else
      render admin_root_path, notice: ['Errors:', todo.errors.full_messages.join(',')].join
    end
  end

  def readonly
    render 'admin/todos/index_readonly'
  end

  private

  def todo
    @todo ||= list.todos.find(params[:id])
  end

  def todos
    @todos ||= list.todos
  end

  def list
    @list ||= if current_user.admin_role? || (current_user.user_role? && params[:action] == 'readonly')
      List.find(params[:list_id])
    else
      current_user.lists.find(params[:list_id])
    end
  end

  def todo_params
    params.require(:todo).permit(:name, :status_id)
  end
end

app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < BaseController
  before_action :todos, only: %i[index]

  def index
  end

  private

  def todos
    @todos ||= list.todos
  end

  def list
    @list ||= List.find(params[:list_id])
  end
end

app/views/admin/todos/_form.html.slim
= f.error_notification
= f.input :name,
        placeholder: t('activerecord.models.todo.attributes.name.placeholder'),
        required: true,
        label: t('name'),
        wrapper: :horizontal_form

= f.input :status_id,
        as: :select,
        label: t('activerecord.models.status.one'),
        label_method: ->(obj){ t("activerecord.models.status.values.name.#{obj.name}") },
        value_method: :id,
        include_blank: true,
        wrapper: :horizontal_form,
        required: true,
        collection: Status.all

app/views/admin/todos/edit.html.slim
= content_for(:title, t('admin.todos.edit'))
= simple_form_for [:admin, @list, @todo] do |f|
  /! Main content
  .content
    .container-fluid
      /! /.container-fluid
      /! /.content
      .row
        .col-md-8
          .card.card-yellow
            .card-header
              = t('admin.todos.edit')
            .card-body
              / - if @todo.image.attached?
              /   div style=("border: 1px solid #28A745; padding: 2px")
              /     = image_tag @todo.image.variant(resize: '200'), alt: @todo.name
              /   = t('admin.todos.remove')
              /   |  #{link_to t('do it'), destroy_image_admin_todo_path(@todo), method: :delete}
              /   p
              / - else
              /   p style=("border: 1px solid #28A745; padding: 2px")
              /     = image_tag 'backend/default-image.jpg', size: 200, alt: 'Photo Image'
              = render partial: 'form', locals: {f: f}
            .card-footer
              = link_to  admin_list_todos_path, class: 'btn btn-danger'
                = t(:cancel)
              = f.submit t(:save), class: 'btn btn-success pull-right'

app/views/admin/todos/index.html.slim
= content_for(:title, @list.name)
/! Main content
.content
  .container-fluid
    /! /.container-fluid
    /! /.content
    .row
      .col-md-6.col-md-offset-10
        = link_to new_admin_list_todo_path(@list), class: 'btn btn-success pull-right'
          i.fas.fa-plus
          |
          = t('admin.todos.add')
    .row
      p

    .row
      .col-12
        .card.card-yellow
          .card-header
            h3.card-title
              = t('admin.todos.list')
          /! /.card-header
          .card-body.p-0
            table.table.table-condensed
              thead
                tr
                  th style=("width: 30px")
                    = t('name')
                  th style=("width: 15px")
                    = t('action')

              tbody
                - @todos.each do |todo|
                  tr
                    td
                      = todo.name
                    td
                      .btn-row
                        = link_to raw('<i class="far fa-edit"></i>'), edit_admin_list_todo_path(@list, todo),
                                class: 'btn btn-sm btn-warning',
                                style: 'margin-right: 10px',
                                title: t('edit')
                        = link_to raw('<i class="far fa-trash-alt"></i>'), admin_list_todo_path(@list, todo),
                                class: 'btn btn-sm btn-warning',
                                method: :delete,
                                data: {confirm: t('confirm')},
                                title: t('remove')
          /! /.card-body

app/views/admin/todos/index_readonly.html.slim
= content_for(:title, @list.name)
/! Main content
.content
  .container-fluid
    /! /.container-fluid
    /! /.content
    .row
      .col-12
        .card.card-yellow
          .card-header
            h3.card-title
              = t('admin.todos.list')
          /! /.card-header
          .card-body.p-0
            table.table.table-condensed
              thead
                tr
                  th style=("width: 30px")
                    = t('name')
              tbody
                - @todos.each do |todo|
                  tr
                    td
                      - if todo.status.name == 'Complete'
                        .todo_complete
                          = todo.name
                      - elsif todo.status.name == 'In progress'
                        div.todo_in_progress
                          = todo.name
                      - else
                        = todo.name
          /! /.card-body

app/views/admin/todos/new.html.slim
= content_for(:title, t('admin.todos.new'))
= simple_form_for [:admin, @list, @todo] do |f|
  /! Main content
  .content
    .container-fluid
      /! /.container-fluid
      /! /.content
      .row
        .col-md-8
          .card.card-yellow
            .card-header
              = t('admin.todos.new')
            .card-body
              = render partial: 'form', locals: {f: f}
            .card-footer
              = link_to  admin_list_todos_path(@list), class: 'btn btn-danger'
                = t(:cancel)
              = f.submit t(:save), class: 'btn btn-success pull-right'