config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|uk|ru/ do
    root to: 'home#show'
    get 'index.html', to: 'home#show'
    resources :lists, only: :index do
      resources :todos, only: :index
    end
    namespace :admin do
      root to: 'home#show'
      get 'readonly', to: 'home#readonly'
      resources :statuses
      resources :accesses
      resources :lists do
        resources :todos do
          get :readonly, on: :collection
          put :done, on: :member
        end
      end
    end

    # devise_for :users,
    #           path_names: {sign_in: 'login',
    #                        sign_out: 'logout',
    #                        password: 'secret',
    #                        sign_up: 'registration'},
    #           controllers: {sessions: 'users/sessions',
    #                         registrations: 'users/registrations',
    #                         passwords: 'users/passwords',
    #                         confirmations: 'users/confirmations',
    #                         unlocks: 'users/unlocks',
    #           }
    devise_for :users, skip: %i[sessions registrations passwords confirmations unlock]
    as :user do
      get 'login.html', to: 'users/sessions#new', as: :new_user_session
      post 'login.html', to: 'users/sessions#create', as: :user_session
      match 'logout.html', to: 'users/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

      get 'registration.html', to: 'users/registrations#new', as: :new_user_registration
      post 'registration.html', to: 'users/registrations#create', as: :user_registration
      get 'edit-registration.html', to: 'users/registrations#edit', as: :edit_user_registration
      patch 'registration.html', to: 'users/registrations#update', as: :patch_user_registration
      delete 'registration.html', to: 'users/registrations#destroy', as: :delete_user_registration
      delete 'remove-avatar/:id', to: 'users/registrations#destroy_avatar', as: :delete_user_avatar_registration

      get 'recover-password.html', to: 'users/passwords#new', as: :new_user_password
      post 'recover-password.html', to: 'users/passwords#create'
      get 'edit-recover-password.html', to: 'users/passwords#edit', as: :edit_user_password
      patch 'recover-password.html', to: 'users/passwords#update', as: :user_password
      put 'recover-password.html', to: 'users/passwords#update'

      get 'confirmation.html', to: 'users/confirmations#new', as: :new_user_confirmation
      get 'show-confirmation.html', to: 'users/confirmations#show', as: :user_confirmation
      post 'show-confirmation.html', to: 'users/confirmations#create'

      get 'unlock.html', to: 'users/unlocks#new', as: :new_user_unlock
      get 'show-unlock.html', to: 'users/unlocks#show', as: :user_unlock
      post 'show-unlock.html', to: 'users/unlocks#create'
    end

     match '*a', to: 'admin/errors#not_found', via: :all unless Rails.env.development?
     # match '*a', to: 'admin/errors#not_found', via: :all
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

class Admin::HomeController < Admin::BaseController
  def show
    @lists = current_user.lists.paginate(page: params[:page], per_page: 2) if current_user.user_role?
    @lists = List.all.paginate(page: params[:page], per_page: 2) if current_user.admin_role?
    @todo = Todo.new
  end

  def readonly
    if current_user.admin_role? || current_user.user_role?
      @lists = List.joins(:access).where(accesses: { name: 'Public' })
                   .or(List.joins(:access).where(accesses: { name: 'Protect' }))
                   .paginate(page: params[:page], per_page: 2)
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < BaseController
  def show
    @lists = List.joins(:access).where(accesses: { name: 'Public' })
                 .paginate(page: params[:page], per_page: 3)
  end
end

app/views/admin/home/_checked_todo.js.html.erb
<script>
$("#customCheckbox<%= todo.id %>").click(function(e, parameters) {

    let nonUI = false;
    try {
        nonUI = parameters.nonUI;
    } catch (e) {}
    let checked = nonUI ? !this.checked : this.checked;
    console.log('print');
    $("#status_update_todo<%= todo.id %>").submit();
});
</script>

app/views/admin/home/_index_readonly_todo.html.slim
tr
  td.th_collapse_todo
    .form-group
  td
    - if todo.status.name == 'Complete'
      .todo_complete
        = todo.name
    - elsif todo.status.name == 'In progress'
      div.todo_in_progress
        = todo.name
    - else
      = todo.name
  td.todo
    .btn-row

app/views/admin/home/_index_todo.html.slim
tr
  td.th_collapse_todo
    .form-group
      .custom-control.custom-checkbox
        = check_box_tag "customCheckbox#{todo.id}", '',
                todo.status.name == 'Complete' ? true : false,
                class: 'custom-control-input'
        = label_tag "customCheckbox#{todo.id}", '', class: 'custom-control-label'
  td
    - if todo.status.name == 'Complete'
      .todo_complete
        = todo.name
    - elsif todo.status.name == 'In progress'
      div.todo_in_progress
        = todo.name
    - else
      = todo.name
  td.todo
    .btn-row
      = link_to raw('<i class="far fa-edit"></i>'), edit_admin_list_todo_path(list, todo),
              class: 'btn btn-sm btn-warning actions_margin_todo',
              title: t('edit')
      = link_to raw('<i class="far fa-trash-alt"></i>'), admin_list_todo_path(list, todo),
              class: 'btn btn-sm btn-warning actions_margin_todo',
              method: :delete,
              data: {confirm: t('confirm')},
              title: t('remove')
= content_for(:custom_script) do
  = render partial: "admin/home/checked_todo.js", locals: {todo: todo}
= form_tag done_admin_list_todo_path(list,todo), id: "status_update_todo#{todo.id}",  method: :put do
  = hidden_field_tag :status_name, todo.status.name == 'Complete' ? 'Incomplete' : 'Complete', id: "status_name_todo#{todo.id}"

app/views/admin/home/_new_todo.html.slim
= simple_form_for [:admin, list, @todo], html: {id: "form_todo#{list.id}"}  do |f|
  = f.error_notification
  = f.input :name,
          placeholder: t('activerecord.models.todo.attributes.name.placeholder'),
          required: true,
          label: t('name'),
          wrapper: :horizontal_form,
          input_html: { id: "todo_name#{list.id}" }


  = f.input :status_id,
          as: :select,
          label: t('activerecord.models.status.one'),
          label_method: ->(obj){ t("activerecord.models.status.values.name.#{obj.name}") },
          value_method: :id,
          include_blank: true,
          wrapper: :horizontal_form,
          required: true,
          collection: Status.all,
          input_html: { id: "todo_status_id#{list.id}" }
  = f.submit t(:save), class: 'btn btn-success pull-right'

app/views/admin/home/readonly.html.slim
= content_for(:title, t('admin.todos.list'))
/! Main content
.content
  .container-fluid
    .accordion#to-do-lists
      .card
        .card-body.p-0
          table.table.table-striped
            thead
              tr.tr_title
                th.th_collapse
                th
                  = t('admin.lists.list')
                th.th_inprogress
                  = t('admin.lists.progress')
    - @lists.each do |list|
      table.table.table-striped
        tbody
          tr
            td.th_collapse
              div.th_collapse id="heading#{list.id}"
                = link_to raw('<i class="fas fa-angle-double-down"></i>'), "#multiCollapseList#{list.id}",
                        style: 'color: grey',
                        title: t('admin.todos.add'),
                        'aria-controls' => "multiCollapseList#{list.id}",
                        'aria-expanded' => 'true',
                        'data-toggle' => 'collapse',
                        role: 'button'
            td.td_list_name
              = link_to readonly_admin_list_todos_path(list), class: 'list'
                = list.name
              .username
                = list.user.username
            td.th_progress
              .progress.progress-xs
                .progress-bar.progress-bar-danger style=("width: #{list.todos_complete}%")
              span.badge.bg-danger
                =  "#{list.todos_complete}%"
            td.th_todos
              .btn-row
                .btn-group
            td.th_actions
              .btn-row
                .btn-group
      div.collapse.multi-collapse id="multiCollapseNewTodos#{list.id}"
        .todo_collapse
          table.table
            tbody
              tr
                td
      div.collapse.show.multi-collapse id="multiCollapseList#{list.id}"
        .todo_new_collapse
          table.table
            tbody
              - list.todos.each do |todo|
                = render partial: "admin/home/index_readonly_todo", locals: {list: list, todo: todo}
                /! /.card-body
                /! /.card
    = will_paginate @lists, list_classes: %w(pagination justify-content-end)
      /! /.container-fluid
      /! /.content

app/views/admin/home/show.html.slim
= content_for(:title, t('admin.todos.list'))
/! Main content
.content
  .container-fluid
    .row
      .col-md-6.col-md-offset-10
        = link_to new_admin_list_path, class: 'btn btn-success pull-right'
          i.fas.fa-plus
          |
          = t('admin.lists.add')
    p
    .accordion#to-do-lists
      .card
        .card-body.p-0
          table.table.table-striped
            thead
              tr.tr_title
                th.th_collapse
                th
                  = t('admin.lists.list')
                th.th_inprogress
                  = t('admin.lists.progress')
                th.th_todos
                  = t('admin.todos.list')
                th.th_actions
                  = t('action')
    - @lists.each do |list|
      table.table.table-striped
        tbody
          tr
            td.th_collapse
              div.th_collapse id="heading#{list.id}"
                = link_to raw('<i class="fas fa-angle-double-down"></i>'), "#multiCollapseList#{list.id}",
                        style: 'color: grey',
                        title: t('admin.todos.add'),
                        'aria-controls' => "multiCollapseList#{list.id}",
                        'aria-expanded' => 'true',
                        'data-toggle' => 'collapse',
                            role: 'button'
            td.td_list_name
              = list.name
              - if current_user.admin_role?
                .username
                  = list.user.username
            td.th_progress
              .progress.progress-xs
                .progress-bar.progress-bar-danger style=("width: #{list.todos_complete}%")
              span.badge.bg-danger
                =  "#{list.todos_complete}%"
            td.th_todos
              .btn-row
                .btn-group
                  = link_to raw('<i class="fas fa-plus"></i>'), "#multiCollapseNewTodos#{list.id}",
                          class: 'btn btn-sm btn-warning',
                          style: 'margin-right: 10px',
                          title: t('admin.todos.add'),
                          'aria-controls' => "multiCollapseNewTodos#{list.id}",
                                  'aria-expanded' => 'false',
                                  'data-toggle' => 'collapse',
                                  role: 'button'
                  = link_to raw('<i class="fas fa-list-ol"></i>'), admin_list_todos_path(list),
                          class: 'btn btn-sm btn-warning',
                          style: 'margin-right: 10px',
                          title: t('admin.todos.list')
            td.th_actions
              .btn-row
                .btn-group
                  = link_to raw('<i class="far fa-edit"></i>'), edit_admin_list_path(list),
                          class: 'btn btn-sm btn-warning actions_margin',
                          title: t('edit')
                  = link_to raw('<i class="far fa-trash-alt"></i>'), admin_list_path(list),
                          class: 'btn btn-sm btn-warning actions_margin',
                          method: :delete,
                          data: {confirm: t('confirm')},
                          title: t('remove')
      div.collapse.multi-collapse id="multiCollapseNewTodos#{list.id}"
        .todo_collapse
          table.table
            tbody
              tr
                td
                  = render partial: 'new_todo', locals: {list: list}
      div.collapse.show.multi-collapse id="multiCollapseList#{list.id}"
        .todo_new_collapse
          table.table
            tbody
              - list.todos.each do |todo|
                = render partial: "admin/home/index_todo", locals: {list: list, todo: todo}
        /! /.card-body
      /! /.card
    = will_paginate @lists, list_classes: %w(pagination justify-content-end)
  /! /.container-fluid
  /! /.content